-- Add sequences and triggers for auto-generated IDs
-- Run this in SQL Developer if you get ORA-01400 (cannot insert NULL into ...ID)
-- Use when tables were created WITHOUT IDENTITY (e.g. Oracle 11g) or manual creation

-- MOVIE
CREATE SEQUENCE MOVIE_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER MOVIE_BI
BEFORE INSERT ON MOVIE FOR EACH ROW
BEGIN
  IF :NEW.MOVIEID IS NULL THEN
    SELECT MOVIE_SEQ.NEXTVAL INTO :NEW.MOVIEID FROM DUAL;
  END IF;
END;
/

-- THEATER
CREATE SEQUENCE THEATER_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER THEATER_BI
BEFORE INSERT ON THEATER FOR EACH ROW
BEGIN
  IF :NEW.THEATERID IS NULL THEN
    SELECT THEATER_SEQ.NEXTVAL INTO :NEW.THEATERID FROM DUAL;
  END IF;
END;
/

-- CUSTOMER
CREATE SEQUENCE CUSTOMER_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER CUSTOMER_BI
BEFORE INSERT ON CUSTOMER FOR EACH ROW
BEGIN
  IF :NEW.CUSTOMERID IS NULL THEN
    SELECT CUSTOMER_SEQ.NEXTVAL INTO :NEW.CUSTOMERID FROM DUAL;
  END IF;
END;
/

-- HALL
CREATE SEQUENCE HALL_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER HALL_BI
BEFORE INSERT ON HALL FOR EACH ROW
BEGIN
  IF :NEW.HALLID IS NULL THEN
    SELECT HALL_SEQ.NEXTVAL INTO :NEW.HALLID FROM DUAL;
  END IF;
END;
/

-- SHOWING
CREATE SEQUENCE SHOWING_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER SHOWING_BI
BEFORE INSERT ON SHOWING FOR EACH ROW
BEGIN
  IF :NEW.SHOWINGID IS NULL THEN
    SELECT SHOWING_SEQ.NEXTVAL INTO :NEW.SHOWINGID FROM DUAL;
  END IF;
END;
/

-- SEAT
CREATE SEQUENCE SEAT_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER SEAT_BI
BEFORE INSERT ON SEAT FOR EACH ROW
BEGIN
  IF :NEW.SEATID IS NULL THEN
    SELECT SEAT_SEQ.NEXTVAL INTO :NEW.SEATID FROM DUAL;
  END IF;
END;
/

-- BOOKING
CREATE SEQUENCE BOOKING_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER BOOKING_BI
BEFORE INSERT ON BOOKING FOR EACH ROW
BEGIN
  IF :NEW.BOOKINGID IS NULL THEN
    SELECT BOOKING_SEQ.NEXTVAL INTO :NEW.BOOKINGID FROM DUAL;
  END IF;
END;
/

-- TICKET
CREATE SEQUENCE TICKET_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TICKET_BI
BEFORE INSERT ON TICKET FOR EACH ROW
BEGIN
  IF :NEW.TICKETID IS NULL THEN
    SELECT TICKET_SEQ.NEXTVAL INTO :NEW.TICKETID FROM DUAL;
  END IF;
END;
/

-- PRICING
CREATE SEQUENCE PRICING_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER PRICING_BI
BEFORE INSERT ON PRICING FOR EACH ROW
BEGIN
  IF :NEW.PRICINGID IS NULL THEN
    SELECT PRICING_SEQ.NEXTVAL INTO :NEW.PRICINGID FROM DUAL;
  END IF;
END;
/

-- PAYMENT
CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER PAYMENT_BI
BEFORE INSERT ON PAYMENT FOR EACH ROW
BEGIN
  IF :NEW.PAYMENTID IS NULL THEN
    SELECT PAYMENT_SEQ.NEXTVAL INTO :NEW.PAYMENTID FROM DUAL;
  END IF;
END;
/
