-- Cinema Ticketing System - Oracle Schema
-- Run as CINEMA_USER or create user and grant privileges first
-- Assumption: Oracle 11g+ (or use XE)

-- Create tables in dependency order
CREATE TABLE THEATER (
  THEATERID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  THEATERNAME VARCHAR2(150) NOT NULL,
  CITY        VARCHAR2(100),
  ADDRESS     VARCHAR2(300),
  CONTACTNUMBER VARCHAR2(20),
  EMAIL       VARCHAR2(100)
);

CREATE TABLE CUSTOMER (
  CUSTOMERID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USERNAME       VARCHAR2(50) NOT NULL UNIQUE,
  FULLNAME       VARCHAR2(150) NOT NULL,
  CUSTOMEREMAIL  VARCHAR2(100) NOT NULL,
  PHONENUMBER    VARCHAR2(20),
  CUSTOMERADDRESS VARCHAR2(300),
  CUSTOMERCITY   VARCHAR2(100),
  DATEOFBIRTH    DATE,
  REGISTRATIONDATE DATE
);

CREATE TABLE MOVIE (
  MOVIEID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITLE       VARCHAR2(200) NOT NULL,
  DURATION    NUMBER(5) NOT NULL,
  LANGUAGE    VARCHAR2(50),
  GENRE       VARCHAR2(100),
  RELEASEDATE DATE
);

CREATE TABLE HALL (
  HALLID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  THEATERID  NUMBER NOT NULL REFERENCES THEATER(THEATERID) ON DELETE CASCADE,
  HALLNUMBER VARCHAR2(20) NOT NULL,
  CAPACITY   NUMBER(5) NOT NULL,
  HALLTYPE   VARCHAR2(50)
);

CREATE TABLE SHOWING (
  SHOWINGID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  HALLID    NUMBER NOT NULL REFERENCES HALL(HALLID) ON DELETE CASCADE,
  MOVIEID   NUMBER NOT NULL REFERENCES MOVIE(MOVIEID) ON DELETE CASCADE,
  SHOWDATE  DATE NOT NULL,
  SHOWTIME  DATE NOT NULL,  -- Oracle uses DATE for time; store as date with time portion
  STATUS    VARCHAR2(20)
);

CREATE TABLE SEAT (
  SEATID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  HALLID    NUMBER NOT NULL REFERENCES HALL(HALLID) ON DELETE CASCADE,
  SEATNUMBER VARCHAR2(20) NOT NULL,
  ROWNUMBER VARCHAR2(10),
  SEATTYPE  VARCHAR2(20)
);

CREATE TABLE BOOKING (
  BOOKINGID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SHOWINGID    NUMBER NOT NULL REFERENCES SHOWING(SHOWINGID) ON DELETE CASCADE,
  CUSTOMERID   NUMBER NOT NULL REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE,
  BOOKINGDATE  DATE,
  BOOKINGTIME  DATE,
  TOTALAMOUNT  NUMBER(10,2),
  PAYMENTSTATUS VARCHAR2(20),  -- 'Paid', 'Pending', 'Cancelled'
  BOOKINGSTATUS VARCHAR2(20),
  PAYMENTMETHOD VARCHAR2(50)
);

CREATE TABLE TICKET (
  TICKETID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BOOKINGID   NUMBER NOT NULL REFERENCES BOOKING(BOOKINGID) ON DELETE CASCADE,
  SEATID      NUMBER NOT NULL REFERENCES SEAT(SEATID) ON DELETE CASCADE,
  TICKETNUMBER VARCHAR2(50) NOT NULL,
  TICKETPRICE NUMBER(10,2) NOT NULL,
  TICKETSTATUS VARCHAR2(20),
  ISSUEDATE   DATE
);

CREATE TABLE PRICING (
  PRICINGID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SHOWINGID      NUMBER REFERENCES SHOWING(SHOWINGID) ON DELETE CASCADE,
  SEATTYPE       VARCHAR2(20),
  ISPUBLICHOLIDAY NUMBER(1) DEFAULT 0,
  ISNEWRELEASEWEEK NUMBER(1) DEFAULT 0,
  BASEPRICE     NUMBER(10,2),
  SURCHARGE     NUMBER(10,2),
  FINALPRICE    NUMBER(10,2)
);

CREATE TABLE PAYMENT (
  PAYMENTID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BOOKINGID    NUMBER REFERENCES BOOKING(BOOKINGID) ON DELETE CASCADE,
  PAYMENTAMOUNT NUMBER(10,2),
  PAYMENTDATE  DATE,
  TRANSACTIONID VARCHAR2(100),
  PAYMENTSTATUS VARCHAR2(20),
  REFUNDAMOUNT NUMBER(10,2)
);
