-- Sample data for Cinema Ticketing System
-- Run after CreateSchema.sql

-- Theaters
INSERT INTO THEATER (THEATERNAME, CITY, ADDRESS, CONTACTNUMBER, EMAIL) 
VALUES ('Cineplex Downtown', 'New York', '123 Main St', '555-0100', 'downtown@cineplex.com');
INSERT INTO THEATER (THEATERNAME, CITY, ADDRESS, CONTACTNUMBER, EMAIL) 
VALUES ('Regal Riverside', 'Los Angeles', '456 River Rd', '555-0200', 'riverside@regal.com');

-- Customers
INSERT INTO CUSTOMER (USERNAME, FULLNAME, CUSTOMEREMAIL, PHONENUMBER, CUSTOMERCITY, REGISTRATIONDATE)
VALUES ('jdoe', 'John Doe', 'john@email.com', '555-1000', 'New York', SYSDATE - 30);
INSERT INTO CUSTOMER (USERNAME, FULLNAME, CUSTOMEREMAIL, PHONENUMBER, CUSTOMERCITY, REGISTRATIONDATE)
VALUES ('jsmith', 'Jane Smith', 'jane@email.com', '555-1001', 'Los Angeles', SYSDATE - 60);

-- Movies
INSERT INTO MOVIE (TITLE, DURATION, LANGUAGE, GENRE, RELEASEDATE)
VALUES ('The Adventure', 120, 'English', 'Action', DATE '2025-01-15');
INSERT INTO MOVIE (TITLE, DURATION, LANGUAGE, GENRE, RELEASEDATE)
VALUES ('Romance Forever', 95, 'English', 'Romance', DATE '2025-02-01');

-- Halls (assuming THEATERID 1 and 2 from above)
INSERT INTO HALL (THEATERID, HALLNUMBER, CAPACITY, HALLTYPE) VALUES (1, '1', 100, 'Standard');
INSERT INTO HALL (THEATERID, HALLNUMBER, CAPACITY, HALLTYPE) VALUES (1, '2', 80, 'VIP');
INSERT INTO HALL (THEATERID, HALLNUMBER, CAPACITY, HALLTYPE) VALUES (2, '1', 120, 'Standard');

-- Seats for Hall 1 (10 rows x 10 seats)
-- Simplified: add a few sample seats
INSERT INTO SEAT (HALLID, SEATNUMBER, ROWNUMBER, SEATTYPE) VALUES (1, '1', 'A', 'Standard');
INSERT INTO SEAT (HALLID, SEATNUMBER, ROWNUMBER, SEATTYPE) VALUES (1, '2', 'A', 'Standard');
INSERT INTO SEAT (HALLID, SEATNUMBER, ROWNUMBER, SEATTYPE) VALUES (1, '1', 'B', 'Standard');
INSERT INTO SEAT (HALLID, SEATNUMBER, ROWNUMBER, SEATTYPE) VALUES (2, '1', 'A', 'VIP');
INSERT INTO SEAT (HALLID, SEATNUMBER, ROWNUMBER, SEATTYPE) VALUES (3, '1', 'A', 'Standard');

-- Showings
INSERT INTO SHOWING (HALLID, MOVIEID, SHOWDATE, SHOWTIME, STATUS)
VALUES (1, 1, SYSDATE - 1, TO_DATE('14:00', 'HH24:MI'), 'Completed');
INSERT INTO SHOWING (HALLID, MOVIEID, SHOWDATE, SHOWTIME, STATUS)
VALUES (1, 2, SYSDATE - 2, TO_DATE('16:30', 'HH24:MI'), 'Completed');
INSERT INTO SHOWING (HALLID, MOVIEID, SHOWDATE, SHOWTIME, STATUS)
VALUES (2, 1, SYSDATE - 3, TO_DATE('18:00', 'HH24:MI'), 'Completed');
INSERT INTO SHOWING (HALLID, MOVIEID, SHOWDATE, SHOWTIME, STATUS)
VALUES (3, 1, SYSDATE - 10, TO_DATE('12:00', 'HH24:MI'), 'Completed');

-- Bookings
INSERT INTO BOOKING (SHOWINGID, CUSTOMERID, BOOKINGDATE, BOOKINGTIME, TOTALAMOUNT, PAYMENTSTATUS, PAYMENTMETHOD)
VALUES (1, 1, SYSDATE - 1, SYSDATE - 1, 25.00, 'Paid', 'Credit');
INSERT INTO BOOKING (SHOWINGID, CUSTOMERID, BOOKINGDATE, BOOKINGTIME, TOTALAMOUNT, PAYMENTSTATUS, PAYMENTMETHOD)
VALUES (2, 1, SYSDATE - 2, SYSDATE - 2, 20.00, 'Paid', 'Cash');
INSERT INTO BOOKING (SHOWINGID, CUSTOMERID, BOOKINGDATE, BOOKINGTIME, TOTALAMOUNT, PAYMENTSTATUS, PAYMENTMETHOD)
VALUES (3, 2, SYSDATE - 3, SYSDATE - 3, 25.00, 'Paid', 'Credit');

-- Tickets
INSERT INTO TICKET (BOOKINGID, SEATID, TICKETNUMBER, TICKETPRICE, TICKETSTATUS, ISSUEDATE)
VALUES (1, 1, 'TKT-001', 12.50, 'Used', SYSDATE - 1);
INSERT INTO TICKET (BOOKINGID, SEATID, TICKETNUMBER, TICKETPRICE, TICKETSTATUS, ISSUEDATE)
VALUES (1, 2, 'TKT-002', 12.50, 'Used', SYSDATE - 1);
INSERT INTO TICKET (BOOKINGID, SEATID, TICKETNUMBER, TICKETPRICE, TICKETSTATUS, ISSUEDATE)
VALUES (2, 3, 'TKT-003', 20.00, 'Used', SYSDATE - 2);
INSERT INTO TICKET (BOOKINGID, SEATID, TICKETNUMBER, TICKETPRICE, TICKETSTATUS, ISSUEDATE)
VALUES (3, 4, 'TKT-004', 25.00, 'Used', SYSDATE - 3);

COMMIT;
